// Nota: Estas listas son abreviadas. 
// Para una aplicación de producción, considera cargarlas desde una API 
// o un archivo más completo para una mejor experiencia de usuario.

export const countries = [
  { name: 'USA', code: 'US' },
  { name: 'MEXICO', code: 'MX' },
];

export const states: { [key: string]: { name: string; code: string }[] } = {
  US: [
    { name: 'Alabama', code: 'AL' },
    { name: 'Alaska', code: 'AK' },
    { name: 'Arizona', code: 'AZ' },
    { name: 'Arkansas', code: 'AR' },
    { name: 'California', code: 'CA' },
    { name: 'Colorado', code: 'CO' },
    { name: 'Connecticut', code: 'CT' },
    { name: 'Delaware', code: 'DE' },
    { name: 'Florida', code: 'FL' },
    { name: 'Georgia', code: 'GA' },
    { name: 'Hawaii', code: 'HI' },
    { name: 'Idaho', code: 'ID' },
    { name: 'Illinois', code: 'IL' },
    { name: 'Indiana', code: 'IN' },
    { name: 'Iowa', code: 'IA' },
    { name: 'Kansas', code: 'KS' },
    { name: 'Kentucky', code: 'KY' },
    { name: 'Louisiana', code: 'LA' },
    { name: 'Maine', code: 'ME' },
    { name: 'Maryland', code: 'MD' },
    { name: 'Massachusetts', code: 'MA' },
    { name: 'Michigan', code: 'MI' },
    { name: 'Minnesota', code: 'MN' },
    { name: 'Mississippi', code: 'MS' },
    { name: 'Missouri', code: 'MO' },
    { name: 'Montana', code: 'MT' },
    { name: 'Nebraska', code: 'NE' },
    { name: 'Nevada', code: 'NV' },
    { name: 'New Hampshire', code: 'NH' },
    { name: 'New Jersey', code: 'NJ' },
    { name: 'New Mexico', code: 'NM' },
    { name: 'New York', code: 'NY' },
    { name: 'North Carolina', code: 'NC' },
    { name: 'North Dakota', code: 'ND' },
    { name: 'Ohio', code: 'OH' },
    { name: 'Oklahoma', code: 'OK' },
    { name: 'Oregon', code: 'OR' },
    { name: 'Pennsylvania', code: 'PA' },
    { name: 'Rhode Island', code: 'RI' },
    { name: 'South Carolina', code: 'SC' },
    { name: 'South Dakota', code: 'SD' },
    { name: 'Tennessee', code: 'TN' },
    { name: 'Texas', code: 'TX' },
    { name: 'Utah', code: 'UT' },
    { name: 'Vermont', code: 'VT' },
    { name: 'Virginia', code: 'VA' },
    { name: 'Washington', code: 'WA' },
    { name: 'West Virginia', code: 'WV' },
    { name: 'Wisconsin', code: 'WI' },
    { name: 'Wyoming', code: 'WY' },
  ],
  MX: [
    { name: 'Aguascalientes', code: 'AG' },
    { name: 'Baja California', code: 'BC' },
    { name: 'Baja California Sur', code: 'BS' },
    { name: 'Campeche', code: 'CM' },
    { name: 'Chiapas', code: 'CS' },
    { name: 'Chihuahua', code: 'CH' },
    { name: 'Coahuila', code: 'CO' },
    { name: 'Colima', code: 'CL' },
    { name: 'Ciudad de México', code: 'CDMX' },
    { name: 'Durango', code: 'DG' },
    { name: 'Guanajuato', code: 'GT' },
    { name: 'Guerrero', code: 'GR' },
    { name: 'Hidalgo', code: 'HG' },
    { name: 'Jalisco', code: 'JA' },
    { name: 'México', code: 'MX' },
    { name: 'Michoacán', code: 'MI' },
    { name: 'Morelos', code: 'MO' },
    { name: 'Nayarit', code: 'NA' },
    { name: 'Nuevo León', code: 'NL' },
    { name: 'Oaxaca', code: 'OA' },
    { name: 'Puebla', code: 'PU' },
    { name: 'Querétaro', code: 'QT' },
    { name: 'Quintana Roo', code: 'QR' },
    { name: 'San Luis Potosí', code: 'SL' },
    { name: 'Sinaloa', code: 'SI' },
    { name: 'Sonora', code: 'SO' },
    { name: 'Tabasco', code: 'TB' },
    { name: 'Tamaulipas', code: 'TM' },
    { name: 'Tlaxcala', code: 'TL' },
    { name: 'Veracruz', code: 'VE' },
    { name: 'Yucatán', code: 'YU' },
    { name: 'Zacatecas', code: 'ZA' },
  ],
};

export const cities: { [key: string]: string[] } = {
  // USA
  AL: ['Birmingham', 'Montgomery', 'Mobile', 'Huntsville', 'Tuscaloosa'],
  AK: ['Anchorage', 'Fairbanks', 'Juneau', 'Sitka', 'Ketchikan'],
  AZ: ['Phoenix', 'Tucson', 'Mesa', 'Chandler', 'Scottsdale', 'Glendale', 'Gilbert'],
  AR: ['Little Rock', 'Fayetteville', 'Fort Smith', 'Springdale', 'Jonesboro'],
  CA: [
    'Anaheim', 'Antioch', 'Bakersfield', 'Berkeley', 'Burbank', 'Carlsbad', 'Chula Vista',
    'Clovis', 'Concord', 'Corona', 'Costa Mesa', 'Daly City', 'Downey', 'El Cajon',
    'El Monte', 'Escondido', 'Fairfield', 'Fontana', 'Fremont', 'Fresno', 'Fullerton',
    'Garden Grove', 'Glendale', 'Hayward', 'Huntington Beach', 'Inglewood', 'Irvine',
    'Lancaster', 'Long Beach', 'Los Angeles', 'Modesto', 'Moreno Valley', 'Murrieta',
    'Oakland', 'Oceanside', 'Ontario', 'Orange', 'Palmdale', 'Pasadena', 'Pomona',
    'Rancho Cucamonga', 'Rialto', 'Richmond', 'Riverside', 'Roseville', 'Sacramento',
    'Salinas', 'San Bernardino', 'San Diego', 'San Francisco', 'San Jose', 'San Mateo',
    'Santa Ana', 'Santa Clara', 'Santa Clarita', 'Santa Maria', 'Simi Valley', 'Stockton',
    'Sunnyvale', 'Temecula', 'Thousand Oaks', 'Torrance', 'Vallejo', 'Ventura',
    'Victorville', 'Visalia'
  ].sort(),
  CO: ['Denver', 'Colorado Springs', 'Aurora', 'Fort Collins', 'Lakewood'],
  CT: ['Bridgeport', 'New Haven', 'Stamford', 'Hartford', 'Waterbury'],
  DE: ['Wilmington', 'Dover', 'Newark', 'Middletown', 'Smyrna'],
  FL: [
    'Cape Coral', 'Clearwater', 'Coral Springs', 'Fort Lauderdale', 'Gainesville', 'Hialeah',
    'Hollywood', 'Jacksonville', 'Miami', 'Miramar', 'Orlando', 'Palm Bay',
    'Pembroke Pines', 'Port St. Lucie', 'St. Petersburg', 'Tallahassee', 'Tampa'
  ].sort(),
  GA: ['Atlanta', 'Augusta', 'Columbus', 'Macon', 'Savannah'],
  HI: ['Honolulu', 'Pearl City', 'Hilo', 'Kailua', 'Waipahu'],
  ID: ['Boise', 'Meridian', 'Nampa', 'Idaho Falls', 'Caldwell'],
  IL: ['Chicago', 'Aurora', 'Joliet', 'Naperville', 'Rockford', 'Springfield'],
  IN: ['Indianapolis', 'Fort Wayne', 'Evansville', 'South Bend', 'Carmel'],
  IA: ['Des Moines', 'Cedar Rapids', 'Davenport', 'Sioux City', 'Iowa City'],
  KS: ['Wichita', 'Overland Park', 'Kansas City', 'Olathe', 'Topeka'],
  KY: ['Louisville', 'Lexington', 'Bowling Green', 'Owensboro', 'Covington'],
  LA: ['New Orleans', 'Baton Rouge', 'Shreveport', 'Lafayette', 'Lake Charles'],
  ME: ['Portland', 'Lewiston', 'Bangor', 'South Portland', 'Auburn'],
  MD: ['Baltimore', 'Columbia', 'Germantown', 'Silver Spring', 'Waldorf'],
  MA: ['Boston', 'Worcester', 'Springfield', 'Cambridge', 'Lowell'],
  MI: ['Detroit', 'Grand Rapids', 'Warren', 'Sterling Heights', 'Ann Arbor'],
  MN: ['Minneapolis', 'Saint Paul', 'Rochester', 'Bloomington', 'Duluth'],
  MS: ['Jackson', 'Gulfport', 'Southaven', 'Hattiesburg', 'Biloxi'],
  MO: ['Kansas City', 'Saint Louis', 'Springfield', 'Columbia', 'Independence'],
  MT: ['Billings', 'Missoula', 'Great Falls', 'Bozeman', 'Butte'],
  NE: ['Omaha', 'Lincoln', 'Bellevue', 'Grand Island', 'Kearney'],
  NV: ['Las Vegas', 'Henderson', 'Reno', 'North Las Vegas', 'Sparks'],
  NH: ['Manchester', 'Nashua', 'Concord', 'Derry', 'Dover'],
  NJ: ['Newark', 'Jersey City', 'Paterson', 'Elizabeth', 'Lakewood'],
  NM: ['Albuquerque', 'Las Cruces', 'Rio Rancho', 'Santa Fe', 'Roswell'],
  NY: ['New York', 'Buffalo', 'Yonkers', 'Rochester', 'Syracuse', 'Albany'],
  NC: ['Charlotte', 'Raleigh', 'Greensboro', 'Durham', 'Winston-Salem'],
  ND: ['Fargo', 'Bismarck', 'Grand Forks', 'Minot', 'West Fargo'],
  OH: ['Columbus', 'Cleveland', 'Cincinnati', 'Toledo', 'Akron'],
  OK: ['Oklahoma City', 'Tulsa', 'Norman', 'Broken Arrow', 'Edmond'],
  OR: ['Portland', 'Salem', 'Eugene', 'Gresham', 'Hillsboro'],
  PA: ['Philadelphia', 'Pittsburgh', 'Allentown', 'Erie', 'Reading'],
  RI: ['Providence', 'Cranston', 'Warwick', 'Pawtucket', 'East Providence'],
  SC: ['Charleston', 'Columbia', 'North Charleston', 'Mount Pleasant', 'Rock Hill'],
  SD: ['Sioux Falls', 'Rapid City', 'Aberdeen', 'Brookings', 'Watertown'],
  TN: ['Nashville', 'Memphis', 'Knoxville', 'Chattanooga', 'Clarksville'],
  TX: [
    'Abilene', 'Amarillo', 'Andrews', 'Arlington', 'Austin', 'Brownsville', 'Carrollton',
    'Corpus Christi', 'Dallas', 'Denton', 'El Paso', 'Fort Stockton', 'Fort Worth', 'Frisco',
    'Garland', 'Grand Prairie', 'Houston', 'Irving', 'Kempner', 'Kermit', 'Killeen',
    'Laredo', 'Lubbock', 'Marion', 'McAllen', 'McKinney', 'Mesquite', 'Midland',
    'Monahans', 'Odessa', 'Ozona', 'Pasadena', 'Pecos', 'Plano', 'San Antonio',
    'Seminole', 'Waco'
  ].sort(),
  UT: [
    'Layton', 'Lehi', 'Logan', 'Millcreek', 'Ogden', 'Orem', 'Provo',
    'Salt Lake City', 'Sandy', 'South Jordan', 'St. George', 'Taylorsville',
    'West Jordan', 'West Valley City'
  ].sort(),
  VT: ['Burlington', 'Essex', 'South Burlington', 'Colchester', 'Rutland'],
  VA: ['Virginia Beach', 'Norfolk', 'Chesapeake', 'Richmond', 'Newport News'],
  WA: ['Seattle', 'Spokane', 'Tacoma', 'Vancouver', 'Bellevue'],
  WV: ['Charleston', 'Huntington', 'Morgantown', 'Parkersburg', 'Wheeling'],
  WI: ['Milwaukee', 'Madison', 'Green Bay', 'Kenosha', 'Racine'],
  WY: ['Cheyenne', 'Casper', 'Laramie', 'Gillette', 'Rock Springs'],

  // Mexico
  AG: ['Aguascalientes', 'Jesús María', 'Calvillo', 'Rincón de Romos'],
  BC: ['Tijuana', 'Mexicali', 'Ensenada', 'Rosarito', 'Tecate'],
  BS: ['La Paz', 'Cabo San Lucas', 'San José del Cabo', 'Comondú', 'Loreto'],
  CM: ['San Francisco de Campeche', 'Ciudad del Carmen', 'Champotón'],
  CS: ['Tuxtla Gutiérrez', 'Tapachula', 'San Cristóbal de las Casas', 'Comitán', 'Palenque'],
  CH: ['Chihuahua', 'Ciudad Juárez', 'Delicias', 'Cuauhtémoc', 'Parral'],
  CO: ['Saltillo', 'Torreón', 'Monclova', 'Piedras Negras', 'Acuña'],
  CL: ['Colima', 'Manzanillo', 'Tecomán', 'Villa de Álvarez'],
  CDMX: ['Ciudad de México'],
  DG: ['Victoria de Durango', 'Gómez Palacio', 'Lerdo', 'Santiago Papasquiaro'],
  GT: ['León', 'Irapuato', 'Celaya', 'Salamanca', 'Guanajuato'],
  GR: ['Acapulco', 'Chilpancingo', 'Iguala', 'Zihuatanejo'],
  HG: ['Pachuca', 'Tulancingo', 'Tula de Allende', 'Tizayuca'],
  JA: ['Guadalajara', 'Zapopan', 'Tlaquepaque', 'Tonalá', 'Puerto Vallarta'],
  MX: ['Toluca', 'Ecatepec', 'Nezahualcóyotl', 'Naucalpan', 'Tlalnepantla'],
  MI: ['Morelia', 'Uruapan', 'Zamora', 'Lázaro Cárdenas', 'Apatzingán'],
  MO: ['Cuernavaca', 'Jiutepec', 'Cuautla', 'Temixco'],
  NA: ['Tepic', 'Bahía de Banderas', 'Compostela', 'Ixtlán del Río'],
  NL: ['Monterrey', 'Guadalupe', 'Apodaca', 'San Nicolás de los Garza', 'San Pedro Garza García'],
  OA: ['Oaxaca de Juárez', 'San Juan Bautista Tuxtepec', 'Salina Cruz', 'Juchitán de Zaragoza'],
  PU: ['Puebla', 'Tehuacán', 'San Martín Texmelucan', 'Cholula', 'Atlixco'],
  QT: ['Santiago de Querétaro', 'San Juan del Río', 'Corregidora', 'El Marqués'],
  QR: ['Cancún', 'Playa del Carmen', 'Chetumal', 'Tulum', 'Cozumel'],
  SL: ['San Luis Potosí', 'Soledad de Graciano Sánchez', 'Ciudad Valles', 'Matehuala'],
  SI: ['Culiacán', 'Mazatlán', 'Los Mochis', 'Guasave'],
  SO: ['Hermosillo', 'Ciudad Obregón', 'Nogales', 'San Luis Río Colorado', 'Guaymas'],
  TB: ['Villahermosa', 'Cárdenas', 'Comalcalco', 'Macuspana'],
  TM: ['Reynosa', 'Heroica Matamoros', 'Nuevo Laredo', 'Tampico', 'Ciudad Victoria'],
  TL: ['Tlaxcala', 'Apizaco', 'Huamantla', 'Chiautempan'],
  VE: ['Veracruz', 'Xalapa', 'Coatzacoalcos', 'Poza Rica', 'Córdoba'],
  YU: ['Mérida', 'Kanasín', 'Valladolid', 'Tizimín'],
  ZA: ['Zacatecas', 'Fresnillo', 'Guadalupe', 'Jerez'],
};
