// Nota: Estas listas son abreviadas. 
// Para una aplicación de producción, considera cargarlas desde una API 
// o un archivo más completo para una mejor experiencia de usuario.

export const countries = [
  { name: 'USA', code: 'US' },
  { name: 'MEXICO', code: 'MX' },
];

export const states: { [key: string]: { name: string; code: string }[] } = {
  US: [
    { name: 'Alabama', code: 'AL' },
    { name: 'Alaska', code: 'AK' },
    { name: 'Arizona', code: 'AZ' },
    { name: 'Arkansas', code: 'AR' },
    { name: 'California', code: 'CA' },
    { name: 'Colorado', code: 'CO' },
    { name: 'Connecticut', code: 'CT' },
    { name: 'Delaware', code: 'DE' },
    { name: 'Florida', code: 'FL' },
    { name: 'Georgia', code: 'GA' },
    { name: 'Hawaii', code: 'HI' },
    { name: 'Idaho', code: 'ID' },
    { name: 'Illinois', code: 'IL' },
    { name: 'Indiana', code: 'IN' },
    { name: 'Iowa', code: 'IA' },
    { name: 'Kansas', code: 'KS' },
    { name: 'Kentucky', code: 'KY' },
    { name: 'Louisiana', code: 'LA' },
    { name: 'Maine', code: 'ME' },
    { name: 'Maryland', code: 'MD' },
    { name: 'Massachusetts', code: 'MA' },
    { name: 'Michigan', code: 'MI' },
    { name: 'Minnesota', code: 'MN' },
    { name: 'Mississippi', code: 'MS' },
    { name: 'Missouri', code: 'MO' },
    { name: 'Montana', code: 'MT' },
    { name: 'Nebraska', code: 'NE' },
    { name: 'Nevada', code: 'NV' },
    { name: 'New Hampshire', code: 'NH' },
    { name: 'New Jersey', code: 'NJ' },
    { name: 'New Mexico', code: 'NM' },
    { name: 'New York', code: 'NY' },
    { name: 'North Carolina', code: 'NC' },
    { name: 'North Dakota', code: 'ND' },
    { name: 'Ohio', code: 'OH' },
    { name: 'Oklahoma', code: 'OK' },
    { name: 'Oregon', code: 'OR' },
    { name: 'Pennsylvania', code: 'PA' },
    { name: 'Rhode Island', code: 'RI' },
    { name: 'South Carolina', code: 'SC' },
    { name: 'South Dakota', code: 'SD' },
    { name: 'Tennessee', code: 'TN' },
    { name: 'Texas', code: 'TX' },
    { name: 'Utah', code: 'UT' },
    { name: 'Vermont', code: 'VT' },
    { name: 'Virginia', code: 'VA' },
    { name: 'Washington', code: 'WA' },
    { name: 'West Virginia', code: 'WV' },
    { name: 'Wisconsin', code: 'WI' },
    { name: 'Wyoming', code: 'WY' },
  ],
  MX: [
    { name: 'Aguascalientes', code: 'AG' },
    { name: 'Baja California', code: 'BC' },
    { name: 'Baja California Sur', code: 'BS' },
    { name: 'Campeche', code: 'CM' },
    { name: 'Chiapas', code: 'CS' },
    { name: 'Chihuahua', code: 'CH' },
    { name: 'Coahuila', code: 'CO' },
    { name: 'Colima', code: 'CL' },
    { name: 'Ciudad de México', code: 'CDMX' },
    { name: 'Durango', code: 'DG' },
    { name: 'Guanajuato', code: 'GT' },
    { name: 'Guerrero', code: 'GR' },
    { name: 'Hidalgo', code: 'HG' },
    { name: 'Jalisco', code: 'JA' },
    { name: 'México', code: 'MX' },
    { name: 'Michoacán', code: 'MI' },
    { name: 'Morelos', code: 'MO' },
    { name: 'Nayarit', code: 'NA' },
    { name: 'Nuevo León', code: 'NL' },
    { name: 'Oaxaca', code: 'OA' },
    { name: 'Puebla', code: 'PU' },
    { name: 'Querétaro', code: 'QT' },
    { name: 'Quintana Roo', code: 'QR' },
    { name: 'San Luis Potosí', code: 'SL' },
    { name: 'Sinaloa', code: 'SI' },
    { name: 'Sonora', code: 'SO' },
    { name: 'Tabasco', code: 'TB' },
    { name: 'Tamaulipas', code: 'TM' },
    { name: 'Tlaxcala', code: 'TL' },
    { name: 'Veracruz', code: 'VE' },
    { name: 'Yucatán', code: 'YU' },
    { name: 'Zacatecas', code: 'ZA' },
  ],
};

export const cities: { [key: string]: string[] } = {
  CA: ['Los Angeles', 'San Francisco', 'San Diego', 'Sacramento', 'San Jose'],
  TX: ['Houston', 'Dallas', 'Austin', 'San Antonio', 'Fort Worth'],
  FL: ['Miami', 'Orlando', 'Tampa', 'Jacksonville', 'Fort Lauderdale'],
  NY: ['New York City', 'Buffalo', 'Rochester', 'Albany', 'Syracuse'],
  IL: ['Chicago', 'Aurora', 'Naperville', 'Joliet', 'Rockford'],
  JA: ['Guadalajara', 'Zapopan', 'Tlaquepaque', 'Tonalá', 'Puerto Vallarta'],
  NL: ['Monterrey', 'San Pedro Garza García', 'Guadalupe', 'Apodaca', 'San Nicolás de los Garza'],
  CDMX: ['Ciudad de México'],
  QR: ['Cancún', 'Playa del Carmen', 'Tulum', 'Cozumel', 'Chetumal'],
  BC: ['Tijuana', 'Mexicali', 'Ensenada', 'Rosarito', 'Tecate'],
};
